version: "{build}"

build:
  verbosity: normal

deploy: off

install:
  ps: |
    bash -c 'curl -Lso stack.zip -L --insecure http://www.stackage.org/stack/windows-i386'
    7z x stack.zip stack.exe
    mkdir C:\stack
    mv stack.exe C:\stack

build_script:
  - set PATH=C:\stack;%PATH%
  - stack setup
  - stack install alex happy
  - stack exec --no-ghc-package-path -- mintty -e pacman -Syuu
  - stack exec --no-ghc-package-path -- mintty -e "pacman -S --needed git tar bsdtar binutils autoconf make xz curl libtool automake python python2 p7zip patch mingw-w64-$(uname -m)-gcc mingw-w64-$(uname -m)-python3-sphinx mingw-w64-$(uname -m)-tools-git"
  - stack exec --no-ghc-package-path -- mintty -e ./boot
  - stack exec --no-ghc-package-path -- mintty -e ./configure --enable-tarball-autodownload
  - stack exec --no-ghc-package-path -- mintty -e make -j8
  - stack exec --no-ghc-package-path -- mintty -e make binary_dist
  - stack exec --no-ghc-package-path -- mintty -e "7z a ghc-windows.zip *.tar.xz"

artifacts:
  - path: ghc-windows.zip
    name: GHC Windows bindist
    type: zip
