version: 2

aliases:
  - &defaults
    working_directory: ~/ghc
    resource_class: xlarge
  - &build-steps
    - checkout
    - run:
        name: prepare-system
        command: .circleci/prepare-system.sh
    - run:
        name: submodules
        command: .circleci/fetch-submodules.sh
    - run:
        name: build
        command: .circleci/build.sh


jobs:
  "validate-x86_64-linux":
    resource_class: xlarge
    docker:
      - image: haskell:8.2
    steps: *build-steps

  "validate-x86_64-freebsd":
    resource_class: xlarge
    docker:
      - image: tweag/toolchain-x86_64-freebsd
    environment:
      TARGET: FreeBSD
    steps: *build-steps

  "validate-x86_64-darwin":
    macos:
      xcode: "9.0"
    steps: *build-steps

workflows:
  version: 2
  validate:
    jobs:
    - validate-x86_64-linux
    - validate-x86_64-freebsd
    - validate-x86_64-darwin
