version: 2

aliases:
  - &defaults
    working_directory: ~/ghc
  - &prepare
    run:
      name: prepare-system
      command: .circleci/prepare-system.sh
  - &submodules
    run:
      name: submodules
      command: .circleci/fetch-submodules.sh
  - &build
    run:
      name: build
      command: .circleci/build.sh


jobs:
  "validate-x86_64-linux":
    resource_class: xlarge
    docker:
      - image: haskell:8.2
    steps:
      # Make sure we have proper openssh before checkout: CircleCI git
      # does not check the repository out properly without it and also
      # takes 20 times longer than it should be.
      - run:
          name: install openssh
          command: |
            apt-get update -qq
            apt-get install -y openssh-client
      - checkout
      - *prepare
      - *submodules
      - *build

  "validate-x86_64-freebsd":
    resource_class: xlarge
    docker:
      - image: tweag/toolchain-x86_64-freebsd
    environment:
      TARGET: FreeBSD
    steps:
      - run:
          name: install git
          command: |
            apt-get update -qq
            apt-get install -qy openssh-client
      - checkout
      - *prepare
      - *submodules
      - *build

  "validate-x86_64-darwin":
    macos:
      xcode: "9.0"
    # OSX comes with git by default so we shouldn't need to pull it in
    steps:
      - checkout
      - *prepare
      - *submodules
      - *build

workflows:
  version: 2
  validate:
    jobs:
    #- validate-x86_64-linux
    - validate-x86_64-freebsd
    - validate-x86_64-darwin
