version: 2

jobs:
  "docker-xlarge":
    resource_class: xlarge
    docker:
      - image: ubuntu
    steps:
      - run: "env"
      - run: "lscpu"

  "docker":
    docker:
      - image: ubuntu
    steps:
      - run: "env"
      - run: "lscpu"

  "macos":
    macos:
      xcode: "9.0"
    steps:
      - run: "sysctl -n hw.ncpu"


workflows:
  version: 2
  validate:
    jobs:
      - docker-xlarge
      - docker
      - macos

